In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b))

32


In [2]:
np.matmul(a, b)

32

In [10]:
a = np.array([[1, 3], [2, 4]])

a

array([[1, 3],
       [2, 4]])

In [11]:
np.transpose(a),a.T

(array([[1, 2],
        [3, 4]]),
 array([[1, 2],
        [3, 4]]))